### ISSUE TITLE
`cat /etc/passwd` doesn't display the fake passwd file

### ISSUE THREAD

**Issue by lstep** [mkishere/sshsyrup#27]
When running in a sshsyrup instance `cat /etc/passwd` (or `cat passwd` when in `/etc`), one doesn't get the fake passwd file but nothing.

**Comment by victpork** [comment]
Because the image zip bundled with software is empty :) You'll have to come up a fake file yourself.

Either you can build your very own fake filesystem image (with gnuzip or the `createfs` tool), or you can put the fake file under the directory `virtualfs.savedFileDir` points to (by default it is `tempdir` in the wd), and you should see the file in the shell.

**Comment by lstep** [comment]
Oh OK, I thought it was reading the `passwd` file (which is available at the root of the repository)
